permalink: '/clanky/:year/:month/:title.html'
paginate_path: "/clanky/strana/:num"
paginate: 5

prose:
    rooturl: '_posts'
    metadata:
        _posts:
            - name: 'title'
              field:
                element: text
                label: 'Titulek'
            - name: 'author'
              field:
                element: text
                label: 'Autor'
            - name: 'photo'
              field:
                element: text
                label: 'Titulní fotka'
                placeholder: 'absolutní URL obrázku'
            - name: 'category'
              field:
                element: select
                label: 'Rubrika'
                options: '_data/rubriky.json'
            - name: 'tags'
              field:
                element: multiselect
                label: 'Témata'
                alterable: true
